version: "3.9"
services:
  keycloak:
    image: "jboss/keycloak"
    ports:
      - "4500:8080"
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: P@ssw0rd2023!
      JAVA_OPTS: -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled
  backend:
    build: './backend'
    ports:
      - "5001:5001"